sonar.projectKey=travel-management-system
sonar.projectName=Travel Management System
sonar.sourceEncoding=UTF-8

# Scan backend + frontend
sonar.sources=Microservices,Frontend-Application/src

# ? CRITICAL for Java analysis
sonar.java.binaries=Microservices/*/target/classes

# Optional but recommended
sonar.java.source=21

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/coverage/**,**/build/**,**/out/**,**/.scannerwork/**,**/*.min.js,**/*.map,**/generated/**
sonar.javascript.exclusions=Frontend-Application/src/**/*.d.ts