spring:
  application:
    name: PAYMENT-SERVICE

  mongodb:
    uri: mongodb://localhost:27017/traveldb


server:
  port: 8083
  ssl:
    enabled: false


# Eureka (Discovery)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


