spring:
  application:
    name: TRAVEL-SERVICE

server:
  port: 8086
  ssl:
    enabled: false


# Eureka (Discovery)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


